CREATE TABLE Task (
    id BIGINT IDENTITY(1,1) PRIMARY KEY,
    title NVARCHAR(150) NOT NULL,
    description NVARCHAR(1000) NULL,
    createdAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    status NVARCHAR(20) NOT NULL,

    CONSTRAINT CK_Task_Status
      CHECK (Status IN ('PENDING', 'IN_PROGRESS', 'COMPLETED'))
);